---
- name: Install nginx
  hosts: localhost
  become: true
  tasks:
  - name: Install nginx
    apt: 
      name: nginx
      state: present

  - name: Enable nginx
    systemd:
      name: nginx
      state: restarted
      enabled: yes

