---
- name: Install php
  hosts: localhost
  become: true
  tasks:
  - name: Install php
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - php
      - php-common
      - php-curl
      - php-gd
      - php-mbstring
      - php-soap
      - php-xml
      - php-xmlrpc
      - php-zip
      - php-fpm
      - php-mysql
      - php-cli
      - php-ldap
      - php-zip
      - php-curl 

  - name: Enable php-fpm
    systemd:
     name: php7.4-fpm
     enabled: yes
